local core = require("acm_core")
describe("parse_completed_key", function()
  it("splits category and name", function()
    local cat, name = core.parse_completed_key("completed_Boss_deerclops")
    assert.are.equal("Boss", cat)
    assert.are.equal("deerclops", name)
  end)
  it("keeps underscores in the name", function()
    local cat, name = core.parse_completed_key("completed_Time_some_long")
    assert.are.equal("Time", cat)
    assert.are.equal("some_long", name)
  end)
  it("returns nil for non-completed keys", function()
    assert.is_nil((core.parse_completed_key("numKilledPig")))
  end)
  it("returns nil for nil / non-string input", function()
    assert.is_nil((core.parse_completed_key(nil)))
    assert.is_nil((core.parse_completed_key(123)))
    assert.is_nil((core.parse_completed_key({})))
  end)
  it("returns nil for malformed completed keys", function()
    assert.is_nil((core.parse_completed_key("completed_")))
    assert.is_nil((core.parse_completed_key("completed_Boss_")))
    assert.is_nil((core.parse_completed_key("completed__x")))
  end)
  it("accepts categories containing digits", function()
    local cat, name = core.parse_completed_key("completed_Boss2_thing")
    assert.are.equal("Boss2", cat)
    assert.are.equal("thing", name)
  end)
end)
