local core = require("acm_core")
describe("parse_completed_key", function()
  it("splits category and name", function()
    local cat, name = core.parse_completed_key("completed_Boss_deerclops")
    assert.are.equal("Boss", cat)
    assert.are.equal("deerclops", name)
  end)
  it("keeps underscores in the name", function()
    local cat, name = core.parse_completed_key("completed_Time_some_long")
    assert.are.equal("Time", cat)
    assert.are.equal("some_long", name)
  end)
  it("returns nil for non-completed keys", function()
    assert.is_nil((core.parse_completed_key("numKilledPig")))
  end)
end)
