local core = require("acm_core")

describe("parse_fraction", function()
  it("parses 'num/max' into two numbers", function()
    local n, m = core.parse_fraction("7/13")
    assert.are.equal(7, n)
    assert.are.equal(13, m)
  end)
  it("parses a zero numerator", function()
    local n, m = core.parse_fraction("0/3")
    assert.are.equal(0, n)
    assert.are.equal(3, m)
  end)
  it("returns nil for non-fraction / non-string input", function()
    assert.is_nil((core.parse_fraction("hello")))
    assert.is_nil((core.parse_fraction("12")))
    assert.is_nil((core.parse_fraction("1/2/3")))
    assert.is_nil((core.parse_fraction(47)))
    assert.is_nil((core.parse_fraction(nil)))
    assert.is_nil((core.parse_fraction(true)))
  end)
end)

describe("normalize_record", function()
  it("keeps a positive number as-is", function()
    assert.are.equal(47, core.normalize_record(47))
  end)
  it("returns the numerator of an 'X/Y' string", function()
    assert.are.equal(7, core.normalize_record("7/13"))
  end)
  it("omits (nil) zero, boolean, nil, and zero fractions", function()
    assert.is_nil(core.normalize_record(0))
    assert.is_nil(core.normalize_record("0/3"))
    assert.is_nil(core.normalize_record(true))
    assert.is_nil(core.normalize_record(false))
    assert.is_nil(core.normalize_record(nil))
    assert.is_nil(core.normalize_record({}))
  end)
end)
